### ISSUE TITLE
Loggin problem

### ISSUE THREAD

**Issue by chemhong** [DarshanPatel11/whatsapp-bot#1]
option.add_argument('--user-data-dir=C:/Users/"Your UserName"/AppData/Local/Google/Chrome/User Data')
driver = webdriver.Chrome('Path to chromedriver.exe', chrome_options=option)

I have changed the path location, but chromedriver has no response to it, still hold on QC code page.
what i need to do to make it work? thanks

**Comment by DarshanPatel11** [comment]
Simple solution is that first login as usual in chrome by scanning QR code and close the browser.
Then run the script, it won't ask to scan again.

**Comment by chemhong** [comment]
I did use the same script you provided, it requested me to scan every time to login, it cannot auto-loggin.... so sad...

**Comment by DarshanPatel11** [comment]
send me the exact error you are getting.

**Comment by chemhong** [comment]
it cannot auto loggin

**Comment by DarshanPatel11** [comment]
https://www.howtogeek.com/255653/how-to-find-your-chrome-profile-folder-on-windows-mac-and-linux/
find path of user profile by using above guide and set it in script.

**Comment by chemhong** [comment]
Thank you guy, I finally solve it, by upgrading all the package include chromedriver.
thank you so much for your grateful help~
